#! /bin/sh

aclocal -I . && \
libtoolize -c --force --automake && \
aclocal -I . && \
autoheader  && \
automake -a -c --gnu || automake -a -c --gnu
autoconf


echo "You can now run \"./configure --enable-developer-mode\" and \"make\""
