#! /bin/sh

aclocal && \
libtoolize -c --force --automake && \
aclocal && \
autoheader  && \
automake -a -c --gnu || automake -a -c --gnu
autoconf

echo "You can now run \"./configure --enable-maintainer-mode\" and \"make\""
