#! /bin/sh

aclocal && \
libtoolize -c --force && \
aclocal && \
autoheader  && \
automake -a -c || automake -a -c
autoconf 

echo "You can now run \"./configure --enable-maintainer-mode\" and \"make\""
