#!/bin/sh

# Copyright (C) 2004, 2005 Free Software Foundation
#
# Author: Simon Josefsson
#
# This file is part of GNUTLS.
#
# GNUTLS is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# GNUTLS is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GNUTLS; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

CERTTOOL=../src/certtool

ret=0
for p12 in 'client.p12 foobar' noclient.p12 unclient.p12; do
    set -- $p12
    file=$1
    passwd=$2
    $CERTTOOL --p12-info --inder --password "$passwd" --infile $file > out 2>&1
    rc=$?
    if test $rc != 0; then
	echo "NEON PKCS12 FATAL $p12"
	ret=1
    else
	echo "NEON PKCS12 OK $p12"
    fi
done
rm -f out

echo "NEON PKCS12 DONE (rc $ret)"
exit $ret
