#!/bin/sh

# Copyright (C) 2004 Free Software Foundation
#
# This file is part of GNUTLS.
#
# GNUTLS is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# GNUTLS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA

CERTTOOL=../src/certtool

test -d pkcs12 || unzip PKITS_data.zip

ret=0
for p12 in pkcs12/*; do
    $CERTTOOL --p12-info --inder --password password --infile $p12 > out 2>&1
    rc=$?
    if test $rc != 0; then
	echo "PKCS12 $p12 FATAL failure."
	ret=1
    fi
done
rm -f out

echo "Done (exit code $ret)"
exit $ret
