#!/bin/sh

# Copyright (C) 2004, 2007, 2010, 2012 Free Software Foundation, Inc.
#
# This file is part of GnuTLS.
#
# GnuTLS is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# GnuTLS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA

srcdir="${srcdir:-.}"
CERTTOOL="${CERTTOOL:-../../src/certtool}"

test -d pkcs12 || unzip "${srcdir}/PKITS_data.zip"

ret=0
for p12 in "${srcdir}/pkcs12"/*; do
	"${CERTTOOL}" --p12-info --inder --password password --infile "${p12}" > out 2>&1
	rc=$?
	if test ${rc} != 0; then
		echo "PKCS12 FATAL $p12"
		ret=1
	fi
done
rm -f out

echo "Done (exit code ${ret})"
exit ${ret}
