#!/bin/sh

# Copyright (C) 2004, 2007, 2010, 2012 Free Software Foundation, Inc.
#
# This file is part of GnuTLS.
#
# GnuTLS is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# GnuTLS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

: ${srcdir=.}
: ${CERTTOOL=../../src/certtool${EXEEXT}}

test -d smime || unzip "${srcdir}/PKITS_data.zip"

ret=0
for msg in "${srcdir}/smime"/*; do
	"${CERTTOOL}" --smime-to-p7 --infile "${msg}" > out 2>&1
	rc=$?
	if test ${rc} != 0; then
		echo "S/MIME FATAL $msg"
		ret=1
	fi
	"${CERTTOOL}" --p7-info --infile out > out2 2>&1
	rc=$?
	if test ${rc} != 0; then
		echo "PKCS#7 FATAL $msg"
		ret=1
	fi
done
rm -f out out2

echo "Done (exit code ${ret})"
exit ${ret}
