#!/bin/sh

# Copyright (C) 2006 Free Software Foundation
#
# Author: Simon Josefsson
#
# This file is part of GNUTLS.
#
# GNUTLS is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# GNUTLS is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GNUTLS; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

set -e

srcdir=${srcdir:-.}
CERTTOOL=${CERTTOOL:-../../src/certtool}

$CERTTOOL --inder --certificate-info \
	  < $srcdir/MD5CollisionCA.cer > ca.pem
$CERTTOOL --inder --certificate-info \
	  < $srcdir/TargetCollidingCertificate1.cer > client1.pem
$CERTTOOL --inder --certificate-info \
	  < $srcdir/TargetCollidingCertificate2.cer > client2.pem

cat client1.pem ca.pem > chain1.pem
cat client2.pem ca.pem > chain2.pem

$CERTTOOL --verify-chain < chain1.pem | tee chain1.log
$CERTTOOL --verify-chain < chain2.pem | tee chain2.log

diff $srcdir/chain1-expect.log chain1.log
diff $srcdir/chain2-expect.log chain2.log

rm -f ca.pem client1.pem client2.pem \
   chain1.pem chain2.pem \
   chain1.log chain2.log

# We're done.
exit 0
