AM_CPPFLAGS = \
	$(CODE_COVERAGE_CPPFLAGS)

AM_CFLAGS = $(WERROR_CFLAGS) $(WSTACK_CFLAGS) $(WARN_CFLAGS) $(NETTLE_CFLAGS) \
  $(LIBTASN1_CFLAGS) $(LIBIDN2_CFLAGS) $(P11_KIT_CFLAGS) $(CODE_COVERAGE_CFLAGS)
COMMON_LINK_LIBS = $(CODE_COVERAGE_LIBS)
