organization: Koko inc.
unit: sleeping dept.
state: Attiki
country: GR
cn: Cindy Lauper
uid: clauper
dn_oid: 2.5.4.12 Dr.
dn_oid: 2.5.4.65 jackal
pkcs9_email: none@none.org
serial: 7
expiration_date: 2015-05-24 14:29:12
activation_date: 2029-01-12 11:36:11
dns_name: www.none.org
dns_name: www.morethanone.org
ip_address: 192.168.1.1
dns_name: www.evenmorethanone.org
email: none@none.org
crl_dist_points: http://www.getcrl.crl/getcrl/
email: where@none.org
ca: 
signing_key: 
cert_signing_key: 
ocsp_signing_key: 
