dn: 2.5.4.9=Arkadias,surName=Mavrogiannopoulos,C=GR,st=Attiki,cn=Nik
serial: 7
expiration_days: 2590
dns_name: www.none.org
dns_name: www.morethanone.org
ip_address: 192.168.1.1
dns_name: www.evenmorethanone.org
email: none@none.org
subject_unique_id: 0015232425
issuer_unique_id: 11142324251224
crl_dist_points: http://www.getcrl.crl/getcrl/
email: where@none.org
ca: 
signing_key: 
cert_signing_key: 
ocsp_signing_key: 
