dn: 2.5.4.9=Arkadias,surName=Mavrogiannopoulos,C=GR,st=Attiki,cn=Nik
serial: 7
expiration_days: 2590
dns_name: www.none.org
dns_name: www.morethanone.org
dns_name: www.evenmorethanone.org
email: none@none.org
crl_dist_points: http://www.getcrl.crl/getcrl/
email: where@none.org
ca: 
signing_key: 
nc_permit_dns: example.com
nc_exclude_dns: net
nc_exclude_dns: org
nc_exclude_dns: 
nc_permit_email: nmav@example.com
nc_exclude_email: example.net
nc_exclude_email: example.li
nc_permit_ip: 192.168.5.0/24
nc_permit_ip: 10.10.10.0/16
nc_permit_ip: 172.23.122.0/23
nc_exclude_ip: 10.10.100.0/24
nc_exclude_ip: 10.10.101.5/24
nc_permit_ip: fc4c:fe8f:7ffa:18bd::/64
nc_exclude_ip: fc4c:fe8f:7ffa:18bd:72c8:64b9::/96
cert_signing_key: 
ocsp_signing_key: 
