dn: 2.5.4.9=Arkadias,surName=Mavrogiannopoulos,C=GR,st=Attiki,cn=Nik
serial: 7
expiration_days: 2590
dns_name: www.none.org
dns_name: www.morethanone.org
other_name: 1.3.6.1.5.2.2 302ca00d1b0b56414e5245494e2e4f5247a11b3019a006020400000002a10f300d1b047269636b1b0561646d696e
other_name_utf8: 1.3.6.1.5.5.7.8.7 nmav@gnutls.org
other_name_utf8: 1.3.6.1.5.5.7.8.5 nmav@gnutls.org
other_name_octet: 1.2.4.5.6 a test string
ip_address: 192.168.1.1
dns_name: www.evenmorethanone.org
email: none@none.org
crl_dist_points: http://www.getcrl.crl/getcrl/
email: where@none.org
ca: 
signing_key: 
cert_signing_key: 
ocsp_signing_key: 
