dn: 2.5.4.9=Arkadias,surName=Mavrogiannopoulos,C=GR,st=Attiki,cn=Nik
serial: 7
expiration_days: 2590
krb5_principal: user@email.domain@KERBEROS.REALM
krb5_principal: user@REALM.COM
krb5_principal: HTTP/user@REALM.COM
krb5_principal: comp1/comp2/user@REALM.COM
ip_address: 192.168.1.1
dns_name: www.evenmorethanone.org
email: none@none.org
crl_dist_points: http://www.getcrl.crl/getcrl/
email: where@none.org
ca: 
signing_key: 
cert_signing_key: 
ocsp_signing_key: 
