#!/bin/sh

# Copyright (C) 2015 Nikos Mavrogiannopoulos
#
# This file is part of GnuTLS.
#
# GnuTLS is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at
# your option) any later version.
#
# GnuTLS is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GnuTLS; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

#set -e

srcdir=${srcdir:-.}
CERTTOOL=${CERTTOOL:-../../src/certtool$EXEEXT}
DIFF=${DIFF:-diff}
if ! test -z "${VALGRIND}";then
VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND} --error-exitcode=15"
fi
OUTFILE=out-pkcs7.tmp

for FILE in single-ca.p7b full.p7b;do
$VALGRIND $CERTTOOL --inder --p7-info --infile $srcdir/$FILE >$OUTFILE
rc=$?

# We're done.
if test "$rc" != "0"; then
  echo "$FILE: PKCS7 decoding failed"
  exit $rc
fi

$DIFF $OUTFILE $FILE.out >/dev/null
if test "$?" != "0"; then
  echo "$FILE: PKCS7 decoding didn't produce the correct file"
  exit 1
fi
done

# check signatures

for FILE in full.p7b;do
$VALGRIND $CERTTOOL --inder --p7-verify --load-ca-certificate $srcdir/../../doc/credentials/x509/ca.pem --infile $srcdir/$FILE >$OUTFILE
rc=$?

if test "$rc" != "0"; then
  echo "$FILE: PKCS7 verification failed"
  exit $rc
fi

$VALGRIND $CERTTOOL --verify-purpose=1.3.6.1.5.5.7.3.1 --inder --p7-verify --load-ca-certificate $srcdir/../../doc/credentials/x509/ca.pem --infile $srcdir/$FILE >$OUTFILE
rc=$?

if test "$rc" != "0"; then
  echo "$FILE: PKCS7 verification failed with key purpose"
  exit $rc
fi

$VALGRIND $CERTTOOL --verify-purpose=1.3.6.1.5.5.7.3.3 --inder --p7-verify --load-ca-certificate $srcdir/../../doc/credentials/x509/ca.pem --infile $srcdir/$FILE >$OUTFILE
rc=$?

if test "$rc" = "0"; then
  echo "$FILE: PKCS7 verification succeeded with wrong key purpose"
  exit 2
fi

done

rm -f $OUTFILE

exit 0
