#!/bin/sh

# Copyright (C) 2004-2012 Free Software Foundation, Inc.
#
# Author: Simon Josefsson
#
# This file is part of GnuTLS.
#
# GnuTLS is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at
# your option) any later version.
#
# GnuTLS is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GnuTLS; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

srcdir=${srcdir:-.}
CERTTOOL=${CERTTOOL:-../../src/certtool$EXEEXT}
DIFF=${DIFF:-diff}
if ! test -z "${VALGRIND}";then
VALGRIND="${LIBTOOL:-libtool} --mode=execute ${VALGRIND}"
fi

# Check for datefudge
TSTAMP=`datefudge "2006-09-23" date -u +%s || true`
if test "$TSTAMP" != "1158962400"; then
    echo "You need datefudge to run this test"
    exit 77
fi

FILES="name-constraints-err.pem"
ERR="1"

set -- $ERR

for i in $FILES; do
datefudge "2014-08-22" \
    $CERTTOOL -e --infile $i > out 2>&1
    rc=$?
    if test $rc != $1; then
	echo "Error in verification of $i."
	cat out
	exit 1
    fi

    $DIFF $srcdir/$i.out out >/dev/null 2>&1
    rc=$?
    if test $rc != 0; then
	echo "Error in verification of $i."
	$DIFF $srcdir/$i.out out
	exit 1
    fi

    shift
done
rm -f out

exit 0
