#include "gnutls_errors.h"

int gnutls_is_fatal_error( int error) {

	switch (error) {
		case GNUTLS_E_MAC_FAILED:
		case GNUTLS_E_UNKNOWN_CIPHER:
		case GNUTLS_E_UNKNOWN_COMPRESSION_ALGORITHM:
		case GNUTLS_E_UNKNOWN_MAC_ALGORITHM:
		case GNUTLS_E_UNKNOWN_ERROR:
		case GNUTLS_E_UNKNOWN_CIPHER_TYPE:
		case GNUTLS_E_LARGE_PACKET:
		case GNUTLS_E_UNSUPPORTED_VERSION_PACKET:
		case GNUTLS_E_UNEXPECTED_PACKET_LENGTH:
		case GNUTLS_E_INVALID_SESSION:
		case GNUTLS_E_UNABLE_SEND_DATA:
		case GNUTLS_E_FATAL_ALERT_RECEIVED:
		case GNUTLS_E_RECEIVED_BAD_MESSAGE:
		case GNUTLS_E_RECEIVED_MORE_DATA:
		case GNUTLS_E_UNEXPECTED_PACKET:
		case GNUTLS_E_CLOSURE_ALERT_RECEIVED:
			return 1;
		case GNUTLS_E_WARNING_ALERT_RECEIVED:
			return 0;
		default:
			return 1;

	}			
}
